---
server:
  port: 8080

spring:
    application:
        name: demo
    profiles:
        active: ${PROFILE:local}
    web:
      locale: en_US
      locale-resolver: fixed

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
