openapi: 3.1.0

info:
  title: "route-api"
  version: "1.0.0"
  description: "route api."
  license:
    name: "Apache-2.0"
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"

paths:
  /hello:
    get:
      tags:
        - "hello"
      description: "Hello"
      operationId: "hello"
      responses:
        200:
          description: "Hello"
          content:
            application/vnd.com_example_demo_api_hello_v1+json:
              schema:
                type: string

components:
  schemas:

    PageResponseV1:
      type: object
      properties:
        total_elements:
          type: integer
          example: 2
        total_pages:
          type: integer
          example: 1
        current_page:
          type: integer
          example: 0
        elements:
          type: array
          items:
            type: object
          example: [ "element1", "element2" ]

    ErrorV1:
      type: object
      properties:
        type:
          type: string
          description: The type of error.
        message:
          type: string
          nullable: true
          description: The error message.
        errors:
          type: object
          additionalProperties:
            type: object
          nullable: false
          description: A map of additional error details.
      required:
        - type

  securitySchemes:
    JwtToken:
      type: http
      scheme: bearer
    AccessToken:
      type: apiKey
      name: Authorization
      in: header
